// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pg.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PGResponse struct {
	Succeed              bool     `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PGResponse) Reset()         { *m = PGResponse{} }
func (m *PGResponse) String() string { return proto.CompactTextString(m) }
func (*PGResponse) ProtoMessage()    {}
func (*PGResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_pg_f0878b0b90ad3dbe, []int{0}
}
func (m *PGResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PGResponse.Unmarshal(m, b)
}
func (m *PGResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PGResponse.Marshal(b, m, deterministic)
}
func (dst *PGResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PGResponse.Merge(dst, src)
}
func (m *PGResponse) XXX_Size() int {
	return xxx_messageInfo_PGResponse.Size(m)
}
func (m *PGResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PGResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PGResponse proto.InternalMessageInfo

func (m *PGResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

type UpdatePostgresqlConfRequest struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	User                 string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	IsMaster             bool     `protobuf:"varint,5,opt,name=is_master,json=isMaster,proto3" json:"is_master,omitempty"`
	IsSlave              bool     `protobuf:"varint,6,opt,name=is_slave,json=isSlave,proto3" json:"is_slave,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePostgresqlConfRequest) Reset()         { *m = UpdatePostgresqlConfRequest{} }
func (m *UpdatePostgresqlConfRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostgresqlConfRequest) ProtoMessage()    {}
func (*UpdatePostgresqlConfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pg_f0878b0b90ad3dbe, []int{1}
}
func (m *UpdatePostgresqlConfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostgresqlConfRequest.Unmarshal(m, b)
}
func (m *UpdatePostgresqlConfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostgresqlConfRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePostgresqlConfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostgresqlConfRequest.Merge(dst, src)
}
func (m *UpdatePostgresqlConfRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostgresqlConfRequest.Size(m)
}
func (m *UpdatePostgresqlConfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostgresqlConfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostgresqlConfRequest proto.InternalMessageInfo

func (m *UpdatePostgresqlConfRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *UpdatePostgresqlConfRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UpdatePostgresqlConfRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdatePostgresqlConfRequest) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *UpdatePostgresqlConfRequest) GetIsMaster() bool {
	if m != nil {
		return m.IsMaster
	}
	return false
}

func (m *UpdatePostgresqlConfRequest) GetIsSlave() bool {
	if m != nil {
		return m.IsSlave
	}
	return false
}

type UpdatePGHBAConfRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	AnotherIp            string   `protobuf:"bytes,2,opt,name=another_ip,json=anotherIp,proto3" json:"another_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePGHBAConfRequest) Reset()         { *m = UpdatePGHBAConfRequest{} }
func (m *UpdatePGHBAConfRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePGHBAConfRequest) ProtoMessage()    {}
func (*UpdatePGHBAConfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pg_f0878b0b90ad3dbe, []int{2}
}
func (m *UpdatePGHBAConfRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePGHBAConfRequest.Unmarshal(m, b)
}
func (m *UpdatePGHBAConfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePGHBAConfRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePGHBAConfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePGHBAConfRequest.Merge(dst, src)
}
func (m *UpdatePGHBAConfRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePGHBAConfRequest.Size(m)
}
func (m *UpdatePGHBAConfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePGHBAConfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePGHBAConfRequest proto.InternalMessageInfo

func (m *UpdatePGHBAConfRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *UpdatePGHBAConfRequest) GetAnotherIp() string {
	if m != nil {
		return m.AnotherIp
	}
	return ""
}

type CreateStandbySignalRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStandbySignalRequest) Reset()         { *m = CreateStandbySignalRequest{} }
func (m *CreateStandbySignalRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStandbySignalRequest) ProtoMessage()    {}
func (*CreateStandbySignalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pg_f0878b0b90ad3dbe, []int{3}
}
func (m *CreateStandbySignalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStandbySignalRequest.Unmarshal(m, b)
}
func (m *CreateStandbySignalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStandbySignalRequest.Marshal(b, m, deterministic)
}
func (dst *CreateStandbySignalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStandbySignalRequest.Merge(dst, src)
}
func (m *CreateStandbySignalRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStandbySignalRequest.Size(m)
}
func (m *CreateStandbySignalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStandbySignalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStandbySignalRequest proto.InternalMessageInfo

type DeleteStandbySignalRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStandbySignalRequest) Reset()         { *m = DeleteStandbySignalRequest{} }
func (m *DeleteStandbySignalRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStandbySignalRequest) ProtoMessage()    {}
func (*DeleteStandbySignalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pg_f0878b0b90ad3dbe, []int{4}
}
func (m *DeleteStandbySignalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStandbySignalRequest.Unmarshal(m, b)
}
func (m *DeleteStandbySignalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStandbySignalRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteStandbySignalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStandbySignalRequest.Merge(dst, src)
}
func (m *DeleteStandbySignalRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStandbySignalRequest.Size(m)
}
func (m *DeleteStandbySignalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStandbySignalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStandbySignalRequest proto.InternalMessageInfo

type RsyncPostgresqlDataRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RsyncPostgresqlDataRequest) Reset()         { *m = RsyncPostgresqlDataRequest{} }
func (m *RsyncPostgresqlDataRequest) String() string { return proto.CompactTextString(m) }
func (*RsyncPostgresqlDataRequest) ProtoMessage()    {}
func (*RsyncPostgresqlDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_pg_f0878b0b90ad3dbe, []int{5}
}
func (m *RsyncPostgresqlDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RsyncPostgresqlDataRequest.Unmarshal(m, b)
}
func (m *RsyncPostgresqlDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RsyncPostgresqlDataRequest.Marshal(b, m, deterministic)
}
func (dst *RsyncPostgresqlDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RsyncPostgresqlDataRequest.Merge(dst, src)
}
func (m *RsyncPostgresqlDataRequest) XXX_Size() int {
	return xxx_messageInfo_RsyncPostgresqlDataRequest.Size(m)
}
func (m *RsyncPostgresqlDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RsyncPostgresqlDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RsyncPostgresqlDataRequest proto.InternalMessageInfo

func (m *RsyncPostgresqlDataRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*PGResponse)(nil), "proto.PGResponse")
	proto.RegisterType((*UpdatePostgresqlConfRequest)(nil), "proto.UpdatePostgresqlConfRequest")
	proto.RegisterType((*UpdatePGHBAConfRequest)(nil), "proto.UpdatePGHBAConfRequest")
	proto.RegisterType((*CreateStandbySignalRequest)(nil), "proto.CreateStandbySignalRequest")
	proto.RegisterType((*DeleteStandbySignalRequest)(nil), "proto.DeleteStandbySignalRequest")
	proto.RegisterType((*RsyncPostgresqlDataRequest)(nil), "proto.RsyncPostgresqlDataRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PGManagerClient is the client API for PGManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PGManagerClient interface {
	UpdatePostgresqlConf(ctx context.Context, in *UpdatePostgresqlConfRequest, opts ...grpc.CallOption) (*PGResponse, error)
	UpdatePGHBAConf(ctx context.Context, in *UpdatePGHBAConfRequest, opts ...grpc.CallOption) (*PGResponse, error)
	CreateStandbySignal(ctx context.Context, in *CreateStandbySignalRequest, opts ...grpc.CallOption) (*PGResponse, error)
	DeleteStandbySignal(ctx context.Context, in *DeleteStandbySignalRequest, opts ...grpc.CallOption) (*PGResponse, error)
	RsyncPostgresqlData(ctx context.Context, in *RsyncPostgresqlDataRequest, opts ...grpc.CallOption) (*PGResponse, error)
}

type pGManagerClient struct {
	cc *grpc.ClientConn
}

func NewPGManagerClient(cc *grpc.ClientConn) PGManagerClient {
	return &pGManagerClient{cc}
}

func (c *pGManagerClient) UpdatePostgresqlConf(ctx context.Context, in *UpdatePostgresqlConfRequest, opts ...grpc.CallOption) (*PGResponse, error) {
	out := new(PGResponse)
	err := c.cc.Invoke(ctx, "/proto.PGManager/UpdatePostgresqlConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pGManagerClient) UpdatePGHBAConf(ctx context.Context, in *UpdatePGHBAConfRequest, opts ...grpc.CallOption) (*PGResponse, error) {
	out := new(PGResponse)
	err := c.cc.Invoke(ctx, "/proto.PGManager/UpdatePGHBAConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pGManagerClient) CreateStandbySignal(ctx context.Context, in *CreateStandbySignalRequest, opts ...grpc.CallOption) (*PGResponse, error) {
	out := new(PGResponse)
	err := c.cc.Invoke(ctx, "/proto.PGManager/CreateStandbySignal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pGManagerClient) DeleteStandbySignal(ctx context.Context, in *DeleteStandbySignalRequest, opts ...grpc.CallOption) (*PGResponse, error) {
	out := new(PGResponse)
	err := c.cc.Invoke(ctx, "/proto.PGManager/DeleteStandbySignal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pGManagerClient) RsyncPostgresqlData(ctx context.Context, in *RsyncPostgresqlDataRequest, opts ...grpc.CallOption) (*PGResponse, error) {
	out := new(PGResponse)
	err := c.cc.Invoke(ctx, "/proto.PGManager/RsyncPostgresqlData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PGManagerServer is the server API for PGManager service.
type PGManagerServer interface {
	UpdatePostgresqlConf(context.Context, *UpdatePostgresqlConfRequest) (*PGResponse, error)
	UpdatePGHBAConf(context.Context, *UpdatePGHBAConfRequest) (*PGResponse, error)
	CreateStandbySignal(context.Context, *CreateStandbySignalRequest) (*PGResponse, error)
	DeleteStandbySignal(context.Context, *DeleteStandbySignalRequest) (*PGResponse, error)
	RsyncPostgresqlData(context.Context, *RsyncPostgresqlDataRequest) (*PGResponse, error)
}

func RegisterPGManagerServer(s *grpc.Server, srv PGManagerServer) {
	s.RegisterService(&_PGManager_serviceDesc, srv)
}

func _PGManager_UpdatePostgresqlConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostgresqlConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PGManagerServer).UpdatePostgresqlConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PGManager/UpdatePostgresqlConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PGManagerServer).UpdatePostgresqlConf(ctx, req.(*UpdatePostgresqlConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PGManager_UpdatePGHBAConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePGHBAConfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PGManagerServer).UpdatePGHBAConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PGManager/UpdatePGHBAConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PGManagerServer).UpdatePGHBAConf(ctx, req.(*UpdatePGHBAConfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PGManager_CreateStandbySignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStandbySignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PGManagerServer).CreateStandbySignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PGManager/CreateStandbySignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PGManagerServer).CreateStandbySignal(ctx, req.(*CreateStandbySignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PGManager_DeleteStandbySignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStandbySignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PGManagerServer).DeleteStandbySignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PGManager/DeleteStandbySignal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PGManagerServer).DeleteStandbySignal(ctx, req.(*DeleteStandbySignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PGManager_RsyncPostgresqlData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsyncPostgresqlDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PGManagerServer).RsyncPostgresqlData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PGManager/RsyncPostgresqlData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PGManagerServer).RsyncPostgresqlData(ctx, req.(*RsyncPostgresqlDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PGManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PGManager",
	HandlerType: (*PGManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdatePostgresqlConf",
			Handler:    _PGManager_UpdatePostgresqlConf_Handler,
		},
		{
			MethodName: "UpdatePGHBAConf",
			Handler:    _PGManager_UpdatePGHBAConf_Handler,
		},
		{
			MethodName: "CreateStandbySignal",
			Handler:    _PGManager_CreateStandbySignal_Handler,
		},
		{
			MethodName: "DeleteStandbySignal",
			Handler:    _PGManager_DeleteStandbySignal_Handler,
		},
		{
			MethodName: "RsyncPostgresqlData",
			Handler:    _PGManager_RsyncPostgresqlData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pg.proto",
}

func init() { proto.RegisterFile("pg.proto", fileDescriptor_pg_f0878b0b90ad3dbe) }

var fileDescriptor_pg_f0878b0b90ad3dbe = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x5f, 0x6b, 0xe2, 0x40,
	0x14, 0xc5, 0x37, 0xeb, 0xbf, 0xe4, 0xc2, 0xb2, 0xec, 0xec, 0xb2, 0xcc, 0xc6, 0x15, 0x6c, 0x1e,
	0x8a, 0x4f, 0x3e, 0xb4, 0xd0, 0xf7, 0x56, 0x8b, 0x2d, 0x45, 0x2a, 0x91, 0x3e, 0xcb, 0x68, 0x6e,
	0x63, 0x20, 0xcd, 0x8c, 0x73, 0xc7, 0x16, 0xbf, 0x45, 0xbf, 0x48, 0xbf, 0x63, 0xc9, 0x18, 0xb5,
	0x95, 0xa4, 0x4f, 0xb9, 0xe7, 0xcc, 0xcd, 0xe1, 0xf0, 0xbb, 0xe0, 0xaa, 0xb8, 0xaf, 0xb4, 0x34,
	0x92, 0x35, 0xec, 0x27, 0x38, 0x05, 0x98, 0x8c, 0x42, 0x24, 0x25, 0x33, 0x42, 0xc6, 0xa1, 0x45,
	0xeb, 0xc5, 0x02, 0x31, 0xe2, 0x4e, 0xd7, 0xe9, 0xb9, 0xe1, 0x4e, 0x06, 0x6f, 0x0e, 0xb4, 0x1f,
	0x54, 0x24, 0x0c, 0x4e, 0x24, 0x99, 0x58, 0x23, 0xad, 0xd2, 0x81, 0xcc, 0x1e, 0x43, 0x5c, 0xad,
	0x91, 0x0c, 0x63, 0x50, 0x5f, 0x4a, 0x32, 0xf6, 0x37, 0x2f, 0xb4, 0x73, 0xee, 0xad, 0x09, 0x35,
	0xff, 0xbe, 0xf5, 0xf2, 0x99, 0xf9, 0xe0, 0x2a, 0x41, 0xf4, 0x22, 0x75, 0xc4, 0x6b, 0xd6, 0xdf,
	0xeb, 0x7c, 0x5f, 0x49, 0x6d, 0x78, 0xbd, 0xeb, 0xf4, 0x7e, 0x84, 0x76, 0x66, 0x6d, 0xf0, 0x12,
	0x9a, 0x3d, 0x09, 0x32, 0xa8, 0x79, 0xc3, 0x76, 0x72, 0x13, 0x1a, 0x5b, 0xcd, 0xfe, 0x81, 0x9b,
	0xd0, 0x8c, 0x52, 0xf1, 0x8c, 0xbc, 0xb9, 0xed, 0x9b, 0xd0, 0x34, 0x97, 0xc1, 0x1d, 0xfc, 0x2d,
	0xea, 0x8e, 0x6e, 0xae, 0x2e, 0x8f, 0x9a, 0xda, 0x56, 0xce, 0x87, 0x56, 0x1d, 0x00, 0x91, 0x49,
	0xb3, 0x44, 0x3d, 0x4b, 0x54, 0xd1, 0xd7, 0x2b, 0x9c, 0x5b, 0x15, 0xfc, 0x07, 0x7f, 0xa0, 0x51,
	0x18, 0x9c, 0x1a, 0x91, 0x45, 0xf3, 0xcd, 0x34, 0x89, 0x33, 0x91, 0x16, 0x81, 0xf9, 0xeb, 0x10,
	0x53, 0xac, 0x78, 0xbd, 0x00, 0x3f, 0xa4, 0x4d, 0xb6, 0x38, 0x60, 0x1b, 0x0a, 0x23, 0x76, 0x65,
	0x38, 0xb4, 0x44, 0x14, 0x69, 0x24, 0x2a, 0xfa, 0xec, 0xe4, 0xd9, 0x6b, 0x0d, 0xbc, 0xc9, 0x68,
	0x2c, 0x32, 0x11, 0xa3, 0x66, 0xf7, 0xf0, 0xa7, 0x8c, 0x3e, 0x0b, 0xb6, 0xd7, 0xec, 0x7f, 0x71,
	0x1a, 0xff, 0x57, 0xb1, 0x73, 0xb8, 0x73, 0xf0, 0x8d, 0x5d, 0xc3, 0xcf, 0x23, 0x3e, 0xac, 0xf3,
	0x39, 0xeb, 0x88, 0x5b, 0x79, 0xcc, 0x18, 0x7e, 0x97, 0x90, 0x61, 0x27, 0xc5, 0x6e, 0x35, 0xb5,
	0xca, 0xb8, 0x12, 0x94, 0xfb, 0xb8, 0x6a, 0xcc, 0x95, 0x71, 0x25, 0xec, 0xf7, 0x71, 0xd5, 0x77,
	0x29, 0x8d, 0x9b, 0x37, 0xad, 0x77, 0xfe, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xc2, 0xfa, 0xab,
	0x45, 0x03, 0x00, 0x00,
}
